trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/**
      - environments/**
      - pipelines/infra.yml
      - backend.tf
      - providers.tf
      - variables.tf
      - outputs.tf

pool:
  vmImage: ubuntu-latest

# =========================
# GLOBAL VARIABLES
# =========================
variables:
- name: LOCATION
  value: westus2

- name: TFSTATE_RESOURCE_GROUP
  value: rg-tfstate-moath

- name: TFSTATE_STORAGE_ACCOUNT
  value: tfstatemoath001

- name: TFSTATE_CONTAINER
  value: tfstate

# =========================
# STAGES
# =========================

# -------- DEV --------
- stage: Dev
  displayName: "Deploy DEV"
  jobs:
  - deployment: Dev
    displayName: "Terraform DEV"
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply DEV
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD_DEV)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/dev

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=dev/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=dev" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

# -------- QA --------
- stage: QA
  displayName: "Deploy QA"
  dependsOn: Dev
  jobs:
  - deployment: QA
    displayName: "Terraform QA"
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply QA
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD_QA)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/qa

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=qa/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=qa" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

# -------- PROD --------
- stage: Prod
  displayName: "Deploy PROD"
  dependsOn: QA
  jobs:
  - deployment: Prod
    displayName: "Terraform PROD"
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply PROD
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD_PROD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/prod

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=prod/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=prod" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"
