trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/**
      - environments/**
      - pipelines/infra.yml
      - backend.tf
      - providers.tf
      - variables.tf
      - outputs.tf

pool:
  vmImage: ubuntu-latest

# =========================
# PARAMETERS
# =========================
parameters:
- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
    - dev
    - qa
    - prod

# =========================
# VARIABLES
# =========================
variables:
- name: LOCATION
  value: westus2

- name: TF_WORKING_DIR
  value: environments/${{ parameters.environment }}

- name: TFSTATE_RESOURCE_GROUP
  value: rg-tfstate-moath

- name: TFSTATE_STORAGE_ACCOUNT
  value: tfstatemoath001

- name: TFSTATE_CONTAINER
  value: tfstate

- name: TFSTATE_KEY
  value: ${{ parameters.environment }}/terraform.tfstate

# =========================
# STAGES
# =========================

# -------- VALIDATE --------
stages:
- stage: Validate
  displayName: "Validate Terraform"
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Validate
      inputs:
        azureSubscription: moath-sp-new
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd $(TF_WORKING_DIR)

          terraform fmt -check -recursive

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=$(TFSTATE_KEY)"

          terraform validate

# -------- PLAN --------
- stage: Plan
  displayName: "Terraform Plan"
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Plan
      env:
        POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
      inputs:
        azureSubscription: moath-sp-new
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd $(TF_WORKING_DIR)

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=$(TFSTATE_KEY)"

          terraform plan \
            -var="environment=${{ parameters.environment }}" \
            -var="location=$(LOCATION)" \
            -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

# -------- APPLY --------
- stage: Apply
  displayName: "Terraform Apply"
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - deployment: Apply
    displayName: "Apply Terraform to ${{ parameters.environment }}"
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            displayName: Install Terraform
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd $(TF_WORKING_DIR)

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=$(TFSTATE_KEY)"

                terraform apply -auto-approve \
                  -var="environment=${{ parameters.environment }}" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"
