trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/**
      - environments/**
      - shared/**
      - pipelines/infra.yml

pool:
  vmImage: ubuntu-latest

variables:
  LOCATION: westus2
  TFSTATE_RESOURCE_GROUP: rg-tfstate-moath
  TFSTATE_STORAGE_ACCOUNT: tfstatemoath001
  TFSTATE_CONTAINER: tfstate

stages:

- stage: Validate
  displayName: "Terraform Validate"
  jobs:
  - job: Validate
    displayName: "Validate Terraform Code"
    steps:
    - checkout: self
      clean: true

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: Bash@3
      displayName: "Terraform Format & Validate"
      inputs:
        targetType: inline
        script: |
          set -e
          terraform fmt -recursive
          terraform init -backend=false
          terraform validate

- stage: Shared
  displayName: "SHARED (ACR)"
  dependsOn: Validate
  jobs:
  - deployment: ApplyShared
    displayName: "Apply SHARED Infrastructure"
    environment: shared
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: "Ensure Terraform backend container"
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az storage container create \
                  --name $(TFSTATE_CONTAINER) \
                  --account-name $(TFSTATE_STORAGE_ACCOUNT) \
                  --auth-mode login

          - task: AzureCLI@2
            displayName: "Terraform Apply (SHARED)"
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd shared

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=shared/terraform.tfstate"

                terraform apply -auto-approve

- stage: Dev
  displayName: "DEV"
  dependsOn: Shared
  jobs:
  - deployment: ApplyDev
    displayName: "Apply DEV Infrastructure"
    environment: dev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: "Terraform Apply (DEV)"
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/dev

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=dev/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=dev" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

- stage: QA
  displayName: "QA"
  dependsOn: Dev
  jobs:
  - deployment: ApplyQA
    displayName: "Apply QA Infrastructure"
    environment: qa
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: "Terraform Apply (QA)"
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/qa

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=qa/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=qa" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

- stage: Prod
  displayName: "PROD"
  dependsOn: QA
  jobs:
  - deployment: ApplyProd
    displayName: "Apply PROD Infrastructure"
    environment: prod
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            clean: true

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: "Terraform Apply (PROD)"
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/prod

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=prod/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=prod" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"
