trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/**
      - environments/**
      - pipelines/infra.yml
      - backend.tf
      - providers.tf
      - variables.tf
      - outputs.tf

pool:
  vmImage: ubuntu-latest

variables:
  LOCATION: westus2

  TFSTATE_RESOURCE_GROUP: rg-tfstate-moath
  TFSTATE_STORAGE_ACCOUNT: tfstatemoath001
  TFSTATE_CONTAINER: tfstate

# =====================================================
# STAGES (DEFINED ONCE)
# =====================================================
stages:

# =====================================================
# VALIDATE (ONCE)
# =====================================================
- stage: Validate
  displayName: "Terraform Validate"
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Validate
      inputs:
        azureSubscription: moath-sp-new
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e

          # Auto-format Terraform files
          terraform fmt -recursive

          # Validate DEV root module
          cd environments/dev
          terraform init -backend=false
          terraform validate


# =====================================================
# DEV
# =====================================================
- stage: Dev
  displayName: "DEV Plan & Apply"
  dependsOn: Validate
  jobs:

  - job: PlanDev
    displayName: "Plan DEV"
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Plan (DEV)
      env:
        POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
      inputs:
        azureSubscription: moath-sp-new
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd environments/dev

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=dev/terraform.tfstate"

          terraform plan \
            -var="environment=dev" \
            -var="location=$(LOCATION)" \
            -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

  - deployment: ApplyDev
    displayName: "Apply DEV"
    environment: dev
    dependsOn: PlanDev
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply (DEV)
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/dev

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=dev/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=dev" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

# =====================================================
# QA
# =====================================================
- stage: QA
  displayName: "QA Plan & Apply"
  dependsOn: Dev
  jobs:

  - job: PlanQA
    displayName: "Plan QA"
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Plan (QA)
      env:
        POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
      inputs:
        azureSubscription: moath-sp-new
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd environments/qa

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=qa/terraform.tfstate"

          terraform plan \
            -var="environment=qa" \
            -var="location=$(LOCATION)" \
            -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

  - deployment: ApplyQA
    displayName: "Apply QA"
    environment: qa
    dependsOn: PlanQA
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply (QA)
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/qa

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=qa/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=qa" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

# =====================================================
# PROD
# =====================================================
- stage: Prod
  displayName: "PROD Plan & Apply"
  dependsOn: QA
  jobs:

  - job: PlanProd
    displayName: "Plan PROD"
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Plan (PROD)
      env:
        POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
      inputs:
        azureSubscription: moath-sp-new
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd environments/prod

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=prod/terraform.tfstate"

          terraform plan \
            -var="environment=prod" \
            -var="location=$(LOCATION)" \
            -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"

  - deployment: ApplyProd
    displayName: "Apply PROD"
    environment: prod
    dependsOn: PlanProd
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply (PROD)
            env:
              POSTGRES_ADMIN_PASSWORD: $(POSTGRES_ADMIN_PASSWORD)
            inputs:
              azureSubscription: moath-sp-new
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -e
                cd environments/prod

                terraform init -reconfigure \
                  -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
                  -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
                  -backend-config="container_name=$(TFSTATE_CONTAINER)" \
                  -backend-config="key=prod/terraform.tfstate"

                terraform apply -auto-approve \
                  -var="environment=prod" \
                  -var="location=$(LOCATION)" \
                  -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD"
