trigger:
  branches:
    include:
      - main
  paths:
    include:
      - modules/**
      - environments/dev/**
      - backend.tf
      - providers.tf
      - variables.tf
      - outputs.tf

pool:
  vmImage: ubuntu-latest

variables:
- group: moath-webapp-dev   # 👈 THIS LINKS THE VARIABLE GROUP

- name: ENVIRONMENT
  value: "dev"

- name: TF_WORKING_DIR
  value: "environments/dev"

- name: TFSTATE_RESOURCE_GROUP
  value: "rg-tfstate-moath"

- name: TFSTATE_STORAGE_ACCOUNT
  value: "tfstatemoath001"

- name: TFSTATE_CONTAINER
  value: "tfstate"

- name: TFSTATE_KEY
  value: "dev/terraform.tfstate"


stages:
- stage: Validate
  displayName: "Validate Terraform (Dev)"
  jobs:
  - job: Validate
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: "latest"

    - task: AzureCLI@2
      displayName: "Terraform validate"
      inputs:
        azureSubscription: "moath-sp-new"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd $(TF_WORKING_DIR)

          terraform version
          terraform fmt -check -recursive

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=$(TFSTATE_KEY)"

          terraform validate

- stage: Plan
  displayName: "Terraform Plan (Dev)"
  dependsOn: Validate
  jobs:
  - job: Plan
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: "latest"

    - task: AzureCLI@2
      displayName: "Terraform plan"
      inputs:
        azureSubscription: "moath-sp-new"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd $(TF_WORKING_DIR)

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=$(TFSTATE_KEY)"

          terraform plan \
            -var="environment=dev" \
            -var="location=eastus" \
            -var="postgres_admin_password=$POSTGRES_ADMIN_PASSWORD_DEV" \
            -out tfplan

- stage: Apply
  displayName: "Terraform Apply (Dev)"
  dependsOn: Plan
  jobs:
  - job: Apply
    steps:
    - checkout: self

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
      displayName: "Install Terraform"
      inputs:
        terraformVersion: "latest"

    - task: AzureCLI@2
      displayName: "Terraform apply"
      inputs:
        azureSubscription: "moath-sp-new"
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          set -e
          cd $(TF_WORKING_DIR)

          terraform init -reconfigure \
            -backend-config="resource_group_name=$(TFSTATE_RESOURCE_GROUP)" \
            -backend-config="storage_account_name=$(TFSTATE_STORAGE_ACCOUNT)" \
            -backend-config="container_name=$(TFSTATE_CONTAINER)" \
            -backend-config="key=$(TFSTATE_KEY)"

          terraform apply -auto-approve tfplan
